### ISSUE TITLE
`timeFmt` called with invalid date in VWaveform

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1324] opened 2022-04-25 12:06 UTC
## Description

https://sentry.io/share/issue/ea8316be37c94b7296c867797cc0dd41/

Not sure why this happens, according to the data Sentry has scraped, we are passing an actual number of seconds for the current time: `6.011812837` (this isn't visible in the shareable Sentry link, but if you have access to the full Sentry page then you can scroll down to the "vue" section and see the `propsData` that was collected)

Going to the search the error is for, `/search/audio?q=lofi` doesn't cause the error for me locally. It is happening frequently though, so I'm prioritizing as high.

## Reproduction

Not sure how to reproduce.

## Environment
According to Sentry this appears to happen almost exclusively to Macs and iPhones with Safari.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment] 2022-04-25 12:07
@WordPress/openverse-frontend This issue requires a Mac and Safari to work on it. Could someone with the appropriate hardware/software setup take a look at this soon?

**Comment by obulat** [comment] 2022-04-25 15:14
I managed to reproduce it on Firefox, too, but can't reproduce it the second time . I searched for 'ears ringing', as in the linked issue, and on 'All content' search result page clicked on the first audio, and got a 404 page.
Also, sometimes when you click on short audios from Freesound, you get `Unexpected value NaN parsing width attribute.` warnings in the console

**Comment by obulat** [comment] 2022-04-25 15:21
`progressBarWidth` can sometimes be NaN...
https://github.com/WordPress/openverse-frontend/blob/7eac75b019f3b3e65462b26c27c82f899d9a7bcf/src/components/VAudioTrack/VWaveform.vue#L370-L373

**Comment by sarayourfriend** [comment] 2022-04-25 15:47
Aha! Good find Olga! I wonder which of those is undefined :thinking:

**Comment by obulat** [comment] 2022-04-26 04:17
There is something wrong with the way the `defaultRef` sets the duration value, @sarayourfriend:
https://github.com/WordPress/openverse-frontend/blob/7eac75b019f3b3e65462b26c27c82f899d9a7bcf/src/components/VAudioTrack/VAudioTrack.vue#L223-L233

I tried debugging, but I can't understand what and how to fix it. For some reason, by the time `localAudio` is available, the `defaultRef`'s value is already set to `NaN`.

**Comment by obulat** [comment] 2022-04-26 04:59
The problem turned out to be in the way `VGlobalAudioTrack` was setting `duration`. It was registering a handler for audio duration change in an audio object watcher. This watcher was firing even when audio object didn't have `duration` property set, which resulted in `NaN` value.

**Comment by zackkrida** [comment] 2022-05-03 20:10
@obulat this is fixed then, I believe? Please close this if so; thank you!

**Closed** 2022-05-05 19:08 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code, 🟨 tech: javascript
