### ISSUE TITLE
Images resize on search results page load

### ISSUE THREAD

**Issue by bengreeley** [WordPress/openverse-frontend#1923] opened 2022-10-19 19:46 UTC
## Description
When I browse search results on the new site there is a slight flicker as images resize to my screen. Though the images resize relatively quickly and users likely don't notice this, I do wonder if this is affecting CLS (Cumulative Layout Shift) scores. It might be worth seeing if this shifting on pageload could be reduced.

## Reproduction
1. Go to https://search-staging.openverse.engineering/search/image?q=dog&ff_new_header=on
2. Observe the results are originally a smaller size and grow to a larger size to fit the screen.

## Screenshots
Screencast: https://d.pr/v/8IC5jL

## Environment
 - Device: Macbook Pro
 - OS: OSX 12.5.1
 - Browser: Chrome
 - Version: 106.0.5249.119 (Official Build) (arm64)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment] 2022-10-19 20:12
Wow, nice find! This is a very peculiar regression I hadn't noticed. CC @WordPress/openverse-frontend

**Comment by sarayourfriend** [comment] 2022-10-20 01:48
@zackkrida I thought I remembered a PR we worked on to fix this issue and it turns out you actually worked to fix this several months ago: https://github.com/WordPress/openverse-frontend/pull/1381

This is definitely a recent regression. I wonder what caused it? The fix for this issue should include a Playwright test to check this, if possible. The linked PR might be a good place to start to look into what differences have been introduced since then that could have caused this regression.

**Comment by zackkrida** [comment] 2022-10-28 22:27
@sarayourfriend that work I did was actually on the single result pages, not on the search result pages. I think this issue may relate to layout/container changes made to the global layout to accommodate the new header.

Big ➕ to the playwright test suggestion.

**Comment by sarayourfriend** [comment] 2022-10-30 19:47
Oh! I misunderstood this issue. Thank you for clarifying it.

**Comment by obulat** [comment] 2022-11-01 04:26
We are rendering the search page as mobile on the server. Then, in the `onMounted` hook, we open the filters if the page width is above `lg` and the `localStorage` value for `areFiltersOpen` isn't set to `false`. This causes the error behavior on the video.

The first solution that came to my mind would be to set the filters open on the first render, and then, in `onMounted`, close them if the width is below `lg` or the `areFiltersOpen` value is set to `false` in `localStorage`. This will probably cause a flicker on mobile widths, though.

I'm not sure about the Playwright test: it will be difficult to test something that's happening during rendering and before the page is fully loaded.

**Comment by obulat** [comment] 2022-11-10 06:10
I've moved this issue from the `new header and footer` milestone to `UI state cookie` milestone because the page load will be fixed there.

**Closed** 2022-12-06 14:12 UTC
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface
