### ISSUE TITLE
Impossible to report a problem

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/openverse-frontend#689] opened 2022-01-23 09:36 UTC
## Description
When trying to report a problem, I occurred an error "Something went wrong, please try again": https://wordpress.org/openverse/photos/808f6e30-7255-424c-b07f-609625a97677
![igp2XbZ](https://user-images.githubusercontent.com/3902621/150672622-3c4abc77-9242-4afb-a2f7-4d1a576f3411.png)

Also reported here:
https://wordpress.slack.com/archives/C02012JB00N/p1642791256114900

**Comment by dhruvkb** [comment] 2022-01-23 19:34
The reason behind this bug was fixed by @obulat in #557 and as such, this bug does cannot be reproduced on `main`. The next deployment to production will fix this.

**Closed** 2022-01-23 19:36 UTC
Labels: ⛔️ status: discarded
