### ISSUE TITLE
Pages menu lacks focus styles

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#875] opened 2022-02-15 17:13 UTC
## Description

The three-dot/pages menu on Openverse lacks focus styles on the interior buttons. 

We should possibly do one or both of the following:

1. We should apply the existing hover styles to focus as well by duplicating them and replacing the `hover:` class prefix with `focus:`.
2. We should apply the standard pink focus outline to the active item

@panchovm @sarayourfriend from an a11y perspective, which approach should we take?

## Reproduction

1. Visit https://wordpress.org/openverse/search/?q=dogs
2. Tab over to the menu
  <img width="79" alt="CleanShot 2022-02-15 at 12 13 10@2x" src="https://user-images.githubusercontent.com/6351754/154113569-058f0631-8860-4758-ab66-b8817fee2ebb.png">
3. Observe that when focusing on items and navigating via keyboard, there is no visual indication.

**Comment by sarayourfriend** [comment] 2022-02-15 17:16
@zackkrida is this caused by the specificity issues? :thinking:

**Comment by zackkrida** [comment] 2022-02-15 17:16
@sarayourfriend I do not think so, as it's live in production.

**Comment by panchovm** [comment] 2022-02-15 17:55
We can use the `search item` component and its styles, used in the **Recent searches** box. The item has very similar paddings and margins. Here is a screenshot of how it might look like.

<img width="300" alt="CleanShot 2022-02-15 at 14 53 54@2x" src="https://user-images.githubusercontent.com/895819/154120405-f260bd34-7036-47f0-9fad-1f9c6e621d7d.png">

The only change is that current component does not have an icon area. In the example above, the spacing between label and icon is `8px`.

If we are ok with this idea, I update the Design Library and Release mockups.

**Comment by sarayourfriend** [comment] 2022-02-15 18:06
I think we can stick with the existing design for this issue and just fix the focus styles? It's a one-line change to fix this:
https://github.com/WordPress/openverse-frontend/pull/876

**Comment by sarayourfriend** [comment] 2022-02-21 15:14
Fixed by Olga's PR based off of https://github.com/WordPress/openverse-frontend/pull/876

**Closed by sarayourfriend** 2022-02-21 15:14 UTC
Labels: good first issue, help wanted, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
