### ISSUE TITLE
Pages menu is cut off in mobile landscape view

### ISSUE THREAD

**Issue by Asadpalasara-multidots** [WordPress/openverse-frontend#1212] opened 2022-03-31 14:16 UTC
## Description
Some of Menu items not visible.

## Reproduction
1. Visit: https://wordpress.org/openverse/
2. Search anything using images search option in search box.
3. Change the screen viewport to the mobile devices.
4. Click on Button(Dots) https://prnt.sc/HutwN50nGtmO
5. Menu items showing till "API"  then rest of items not visible.

## Screenshots
https://prnt.sc/aUuprxKjkp2m

## Environment
 - Device: iPhone 12 Pro Landscape mode
 - Browser: Chrome

**Comment by krysal** [comment] 2022-03-31 21:35
Thanks for reporting this issue with all details @Asadpalasara-multidots. We'll work on general improvements for the whole header. CC @panchovm.

**Comment by panchovm** [comment] 2022-04-05 21:21
I can not reproduce the bug. Once reaching step 3 to see mobile views, the header changes and shows secondary menu's items inside the content switcher modal. See [this gif](https://cln.sh/6fD1Vk).

**Comment by krysal** [comment] 2022-05-03 12:56
@panchovm Try in an actual phone, not the browser emulator, that gives you the limited height that prevents seeing the whole dropdown menu, as @Asadpalasara-multidots shown in the screenshot.

**Comment by sarayourfriend** [comment] 2022-05-04 19:05
Changing the horizontal breakpoint probably doesn't fix the problem. If you have a wide but short device (like a horizontal smartphone, or a browser window aligned to the top half of your screen) this still happens.

We could make the inside of the menu scrollable?

**Comment by panchovm** [comment] 2022-05-05 17:10
Most devices' aspect ratios display the content in a proper layout, so the challenge seems to be picking a breakpoint where the navigation adapts correctly, as both navigational elements and search results, whether it is landscape or portrait. On desktop, or where you can control the browser size, there will always be cases of cutting the UI due to window size.

The scrollable menu sounds reasonable for this case, but I can not envision a smooth interaction in other situations unless you are thinking of special conditions for this behavior.

**Comment by zackkrida** [comment] 2022-05-05 18:41
The core issue, to my mind, is having a sticky header combined with flyout/dropdown menus. This means that the height of the dropdowns can never exceed the user's screen height, which is a difficult thing to always guarantee. We'd have to find a way to use javascript to make sure the dropdowns are scrollable and never extend past the bottom edge of the viewport.

**Comment by sarayourfriend** [comment] 2022-05-06 07:58
@zackkrida if we set `max-height: calc(100vh - var(--button-height) - var(--header-top-padding))` or something like that, it'd solve that, right? Kind of ugly but :grimacing:

**Comment by zackkrida** [comment] 2022-05-06 14:22
That is true, and I guess we'd want to get those heights with refs. It does work pretty well, here's a hardcoded example:

![CleanShot 2022-05-06 at 10 21 27@2x](https://user-images.githubusercontent.com/6351754/167152304-d1400618-9103-49a3-847d-44c041ce01f9.png)

**Comment by sarayourfriend** [comment] 2022-05-06 14:42
That's kind of the thing with Tailwind, I'm not sure exactly how to do an escape hatch to be able to easily use variables for other things that need to reference shared sizes.

In this case I guess it's okay for it to use JS to calculate the variables because the menus are never open in the SSR render anyway.

**Comment by panchovm** [comment] 2022-05-23 22:29
As @zackkrida commented on PR #1257, this issue was not tackled in the code merged.

I wonder if we should set a header component shift based on the viewport's height, similar to the breakpoints logic. After seeing the image attached in the initial comment and [this example](https://user-images.githubusercontent.com/6351754/167152304-d1400618-9103-49a3-847d-44c041ce01f9.png), it might work using the [header mobile](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=751%3A2808) version and show all actions in full-size menus.

**Comment by sarayourfriend** [comment] 2022-05-24 10:18
We could use the `max-height` media query for that... Do you have any ideas for how tall the viewport would need to be for us to consider it a horizontally oriented mobile display?

**Comment by panchovm** [comment] 2022-05-24 21:31
I am trying to find stats about smartphone screen sizes and only found [this site](https://screensiz.es/). It seems that `16:9` is the most widespread aspect ratio.

Since this might happen mostly on mobile devices, we can try calculating the viewport size in devices smaller than `sm` breakpoint and, if height is smaller than width, then shift to the mobile header. Likely I am missing some other inputs, but my point is detecting the device's landscape view as the criterion for the change.

**Comment by zackkrida** [comment] 2022-07-05 15:20
The best fix here is probably to make sure if _any_ of our popovers extend outside of the viewport, that we constrain their height and apply an internal scrollbar. 

I'm going to mark this as 'help wanted', since it's likely someone in the community interested in frontend work could take this on.

**Comment by panchovm** [comment] 2022-08-23 20:26
Removing the `needs design` label as #1686 is developing a solution.

**Closed** 2022-08-26 09:31 UTC
Labels: bug, help wanted, 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface
