### ISSUE TITLE
Playing two audio tracks at once

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1426] opened 2022-05-12 17:14 UTC
## Description
On a small breakpoint, you can play an audio track over another already-playing audio track and can not close the global audio player. Reported by @obulat 

## Reproduction
1. Search for audios and stay on the search results page.
2. Click **Play** on any audio to open the global audio player.
3. Click on an audio title to see the single result view. The global audio player should be playing the audio.
4. Scroll down to the **Related audio** area and play any other audio.
5. Hear the error: Both audio tracks are playing simultaneously over each other.

## Additional context
* Closed issue that fixed the non-stop playing audio. #775
* Related issue for the global audio player. #873

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment] 2022-05-12 17:26
I couldn't reproduce this issue on the newly-deployed version (search-dev.openverse.engineering). Could  someone else try reproducing, and close this issue if you also cannot see it, @openverse-frontend?

**Comment by panchovm** [comment] 2022-05-12 19:05
I was able to see the bug in staging, but I changed one step of your initial ones as it did not work for me.

**Comment by zackkrida** [comment] 2022-05-13 00:02
I am also not able to reproduce in production; please re-open this issue if anyone encounters it again.

**Closed by zackkrida** 2022-05-13 00:02 UTC
Labels: 🟧 priority: high, 🛠 goal: fix
