### ISSUE TITLE
Fixed footer when loading more images

### ISSUE THREAD

**Issue by pedroarellano** [WordPress/openverse-frontend#834] opened 2022-02-08 19:19 UTC
When loading more images the footer stay fixed reducing the search results area.

This issue was recorded in osx monterrey v 12.1 and Firefox 96.0.2

https://user-images.githubusercontent.com/2279641/153059093-f4386fca-a7b2-4603-bd04-d770c87b3818.mp4

**Comment by panchovm** [comment] 2022-02-11 17:16
Thanks for bringing this. I would assume that this relates to having openverse as an iframe in the WP site, but @WordPress/openverse-frontend crew must know better and can link other existing issues or ongoing PRs.

**Comment by sarayourfriend** [comment] 2022-02-11 18:34
Yup, it's definitely an iframe problem. Iframes have weird behaviors around scrolling on desktop and mobile.

I'm not sure how to fix this, maybe we need to `postMessage` to the parent frame when loading new results to change the height of the iframe or something.

We're also actively working to try to remove the limitation of the iframe.

**Comment by zackkrida** [comment] 2022-02-11 18:56
This would be fixed by something discussed previously: Updating the iframe to be `100vh - headerHeight` and hiding overflow in the WP theme. Which would block access to the wp.org footer, but provide users much more screen space for using Openverse. 

This would likely be a worthwhile addition while we continue to discuss eliminating the iframe.

**Comment by sarayourfriend** [comment] 2022-02-22 17:02
@zackkrida do you know if anyone is working on the iframe height fix?

**Comment by zackkrida** [comment] 2022-02-22 17:03
I don't believe so.

**Comment by zackkrida** [comment] 2022-02-22 17:11
@sarayourfriend sorry, the problem is that the value of `--header-height: 117px;` is incorrect, not that this code doesn't exist!

**Comment by sarayourfriend** [comment] 2022-02-22 17:23
Fix incoming in https://github.com/WordPress/wordpress.org/pull/62

**Comment by dd32** [comment] 2022-03-09 07:15
https://github.com/WordPress/wordpress.org/pull/62 merged

**Closed** 2022-03-09 11:06 UTC
Labels: bug, good first issue, help wanted, 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface
