### ISSUE TITLE
Combine image cell components

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1007] opened 2022-02-25 16:40 UTC
## Problem

We currently have two image cell components:

- One that displays as a square in the all results grid
- One that preserves the image aspect ratio in the image results grid

These share a lot of logic and styles, and without unifying them they may fall out of sync with each other in terms of a11y and functionality, as they did _prior to_ this PR #1006 .

## Description

[ticket work required. technical details to follow]

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment] 2022-04-01 16:28
Duplicate of #1033, closing in favor of that one as it has more technical details.

**Closed by krysal** 2022-04-01 16:28 UTC
Labels: 🟩 priority: low, 🧹 status: ticket work required, ✨ goal: improvement, 💻 aspect: code
