### ISSUE TITLE
If there are 0 audio results on the All Content view (but some images), the Load more button is not clickable

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1301] opened 2022-04-20 06:40 UTC
## Description

Example: https://search-staging.openverse.engineering/search/?q=%F0%9F%90%88

Go to that search and try to use the load more button, it is unresponsive.

Originally reported by @obulat 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by Godwindaniel10** [comment] 2022-04-20 10:45
Hi @sarayourfriend , the issue is that, the button has been set to disabled . inpect on the load more button , go to the html , you will see as below , try editing the html by removing the disbaled , then try it out it will load .the after that you can change that setting in your html code or css
![image](https://user-images.githubusercontent.com/54848535/164214152-9cdb9c07-ef46-407b-b7ca-288c8b482e7c.png)

**Comment by Godwindaniel10** [comment] 2022-04-20 10:48
https://www.loom.com/share/8e1855ea8b114085a01f5cc932bf109a

**Comment by sarayourfriend** [comment] 2022-04-20 13:55
@Godwindaniel10 yup! The reason why the button is disabled in that situation is the real question we need to answer to solve the issue :slightly_smiling_face: If you want to debug the issue I'd suggest looking at the `VLoadMore` component.

**Comment by Godwindaniel10** [comment] 2022-04-20 14:58
@sarayourfriend guess im finding it had to run dev server, i followed the readme intruc

**Comment by obulat** [comment] 2022-04-20 15:27
Oh, the problem wasn't in the emoji! 'Load More' button is disabled when there are 0 audio results, but some image results on the All Content view. #1238 could possibly fix this issue.

**Comment by obulat** [comment] 2022-04-20 16:58
Oh, I checked #1238, and it indeed fixes this issue. I merged main into it and marked it ready for review.

**Closed** 2022-05-02 17:17 UTC
Labels: help wanted, 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface
