### ISSUE TITLE
License icons in the filters sidebar are misaligned when scrollbar is visible

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1412] opened 2022-05-11 13:13 UTC
## Description

The icons are vertically-aligned, and when the license name spans more than one line, it looks bad.

## Reproduction

1. Open the filters sidebar and look at the licenses filters.

## Screenshots

Note the last 2 rows here:
<img width="254" alt="Screen Shot 2022-05-11 at 3 51 43 PM" src="https://user-images.githubusercontent.com/15233243/167858037-11c821bf-a14a-4af9-a32a-7d28fbde128a.png">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment] 2022-05-11 13:35
@obulat I wonder if we should simply make the sidebar wider to accommodate these. These strings aren't translated, right? so they'll consistently be the same length.

**Comment by obulat** [comment] 2022-05-11 13:40
Public Domain Mark is translated, and it can be long.

**Comment by sarayourfriend** [comment] 2022-05-11 16:10
Can we float the checkbox vertically, so it's aligned with the icons? At least a stop-gap until we discover a different way to present these that wouldn't have this problem.

**Comment by zackkrida** [comment] 2022-05-11 16:25
Making each row top-aligned instead of center aligned should do what @sarayourfriend is reccommending 👍

**Comment by zackkrida** [comment] 2022-05-11 16:43
Wait @obulat under which conditions does the sidebar appear this way? I'm not able to replicate. Is browser zoom or the default font size modified in your example in any way?

Seeing the following locally and in staging:

![CleanShot 2022-05-11 at 12 41 12@2x](https://user-images.githubusercontent.com/6351754/167903114-80fb97ea-7c22-4115-b3d4-526f90ea709b.png)

**Comment by obulat** [comment] 2022-05-11 19:17
I tried search-staging on Chrome, Samsung browser and Firefox on Android, and I can only replicate this in landscape Firefox. Can this be related to cache?

**Comment by sarayourfriend** [comment] 2022-05-11 21:16
![Screenshot_20220511-221535](https://user-images.githubusercontent.com/24264157/167949090-6708f3b5-74f6-437a-8a96-d35dac38a91c.png)

My phone might be wider but I can't reproduce it on Firefox for Android, FWIW.

**Comment by obulat** [comment] 2022-05-12 04:08
I was really confused about why I'm seeing this in some places and not the other, and then I found the reason when resizing the window for recording the gif: When the scrollbar appears, there's not enough room for everything to fit, so the icons center on 2 rows instead of one.
We could say that we don't translate the icons so they will never be too long, but there's the Public Domain mark that _is_ translated. We could also replace the Public Domain with PDM, which might make all the items here more consistent.

**Comment by sarayourfriend** [comment] 2022-05-12 05:47
@zackkrida can you try with show scrollbars enabled on mac os?

**Comment by zackkrida** [comment] 2022-12-07 13:56
Closing in favor of #2028, which has more details on the fix and is soon to have a linked PR.

**Closed by zackkrida** 2022-12-07 13:56 UTC
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface
