### ISSUE TITLE
Header size in tablet

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#759] opened 2022-01-31 15:20 UTC
## Description
On tablet, `md` and `lg` breakpoints, the header breaks when opening the content switcher by changing its height and moving buttons to a second row.

## Expectation
The header should not change its size but adapt its width to the viewport.

## Screenshots

https://user-images.githubusercontent.com/895819/151820437-417db89f-9839-471a-a8fa-6cdfdc873725.mp4

https://user-images.githubusercontent.com/895819/151820462-7d33eeb8-d793-4145-80ec-daace36f0f01.mp4

**Comment by zackkrida** [comment] 2022-02-01 12:30
I'm not able to reproduce this on the production site in Chrome, Firefox, or Safari on my Mac. I can get you specific version numbers on those, but where are you seeing this issue?

**Comment by panchovm** [comment] 2022-02-01 13:11
On Firefox and Safari, in an iPad Pro 11-inch. Sorry for not adding the device and browser details.

**Comment by sarayourfriend** [comment] 2022-02-02 12:53
@panchovm can you share what version if iPadOS your device is running? You can find it by following these steps: https://support.apple.com/en-us/HT201685

**Comment by panchovm** [comment] 2022-02-02 13:42
I update the OS yesterday but today I am still seeing the bug. I have iOS 15.3

I think it has to do with the WordPress header. In the video below, I was trying to change content, see filters, and type a new search. None of them worked.

https://user-images.githubusercontent.com/895819/152164966-185ad0e5-77d0-473c-968f-fa8464b203e6.mp4

**Comment by sarayourfriend** [comment] 2022-02-02 13:58
Sounds good. I have an iPad I can test this with back home. I'll look into this later today unless someone else gets to it before me.

**Comment by zackkrida** [comment] 2022-02-08 00:12
@panchovm or @sarayourfriend could you check the `main` branch for this again on an iPad? it might have been fixed in a recent PR.

**Comment by obulat** [comment] 2022-02-08 15:34
There is a new regression on the `main` branch due to addition of the `VLogoButton`. Originally, the search bar width in a single-row header was calculated based on the widths of other components, and the logo was assumed to be 40px wide. Now it takes up 48px, so the search bar doesn't fit, and the last button goes to the second row.

**Comment by panchovm** [comment] 2022-02-09 11:42
I do not know how to set up my iPad for running dev, I tried mirroring it from my MacBook but did not work.

**Comment by sarayourfriend** [comment] 2022-02-09 13:05
I ran it yesterday and didn't notice this particular issue. But there are indeed other problems with mobile browsing and the header that we need to fix (I'm working on it last night and today).

**Comment by panchovm** [comment] 2022-02-09 19:04
This is what I see on Firefox and Safari (iOS 15.3)

https://user-images.githubusercontent.com/895819/153271457-a6fef236-55dd-4a46-92cb-b32bc536c6fc.mp4

https://user-images.githubusercontent.com/895819/153271473-50f42d3a-0113-42e4-98bf-0f9195dff2c1.mp4

**Comment by sarayourfriend** [comment] 2022-02-22 16:16
I think the fixes to the popover height/width in #850 might actually solve this. It's very similar behavior to what I was seeing in iOS with the license description button moving around with the popover.

**Comment by sarayourfriend** [comment] 2022-02-23 12:04
Closed by https://github.com/WordPress/openverse-frontend/pull/850

**Closed by sarayourfriend** 2022-02-23 12:04 UTC
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
