### ISSUE TITLE
The header is not fixed when scrolling to bottom

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#2150] opened 2023-02-07 08:37 UTC
## Description
The header is not fixed. If you scroll down, you will see it disappear.

## Reproduction

 On staging.openverse.org, search for images and scroll down. You will see that after some point, the header scrolls up and disappears from the screen:

## Screenshots
![Kapture 2023-02-07 at 11 23 39](https://user-images.githubusercontent.com/15233243/217192316-7da863bb-6a76-4ff9-93e5-9b159df6b45a.gif)

## Additional context
~~Thankfully, there's an easy fix: adding `overflow-y-scroll` to `app`~~ It's not enough.

**Comment by zackkrida** [comment] 2023-02-07 12:03
Related to this, it looks like the global audio player now floats around once you scroll past a certain point. 

Assuming this is related to the changes to fix the homepage height. 

![Screenshot_20230207-070206.png](https://user-images.githubusercontent.com/6351754/217239767-49ccd155-4d87-4dba-8e9a-36de09fe9b69.png)

**Comment by zackkrida** [comment] 2023-02-07 12:26
Yep, I can confirm these issues are fixed by updating the interior pages back to using min-height instead of height for setting the page to 100vh or dvh.

**Closed** 2023-02-08 06:44 UTC
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface
