### ISSUE TITLE
Large blank section in playwright test output

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1471] opened 2022-05-25 18:01 UTC
Our playwright test action has a large section of hundreds of blank lines which can make reading the output difficult, especially if you forget about the problem and think you've reached the end of the output.

Here's an example: https://github.com/WordPress/openverse-frontend/runs/6597323083?check_suite_focus=true#step:4:5351

**Comment by obulat** [comment] 2022-05-26 05:58
Sometimes all of the logs for found/not-found tapes are not displayed and you see them as blank lines in the output. I didn't see any blank lines in the linked log, but I did see A LOT of '... tape found' logs which actually make the logs not really useful.
We might want to silence the talkback proxy even if then we will not see the 'tape not found' logs, too. I couldn't find a way to only keep the latter and stop showing the former, as they are of the same log level.

**Comment by obulat** [comment] 2022-11-18 19:14
Closing this issue because it was caused by the GitHub UI momentarily showing a lot of blank space instead of the log lines. If you scrolled up and down and waited, you would see the logs.

**Closed by obulat** 2022-11-18 19:14 UTC
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx
