### ISSUE TITLE
Mobile audio results using incorrect audio track layout

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1278] opened 2022-04-15 00:42 UTC
## Description

The audio results isn't switching to the correct track layout on small displays.

## Reproduction

1. View https://wordpress.org/openverse/search/audio?q=dog on a mobile device
2. Observe incorrect audio layout

## Screenshots

<img width="452" alt="CleanShot 2022-04-14 at 20 42 17@2x" src="https://user-images.githubusercontent.com/6351754/163498473-112eca5e-f77b-41ed-b188-8526ea339d49.png">

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment] 2022-04-15 07:14
Appears to be iframe specific (or it's fixed in `main`) I can't reproduce this on staging.

**Comment by zackkrida** [comment] 2022-04-15 11:48
Hm, if I go to https://search-staging.openverse.engineering/search/audio?q=dog and make the browser as narrow as possible, it looks like the screenshot above.

**Comment by sarayourfriend** [comment] 2022-04-15 12:04
@zackkrida it seems to only work with a mobile browser UA! I can reproduce if I just narrow my browser but if I use the mobile browser emulation in Firefox it works fine. It does work correctly on my phone, FWIW.

Hopefully that means this is less of a problem than it appears to be and isn't going to effect actual mobile clients, just very narrow desktop browser viewports (still a problem but not as bad as if all mobile browsers were affected)

**Comment by zackkrida** [comment] 2022-04-15 12:36
@sarayourfriend yep, I'm seeing that too! That's a relief 😓.

**Comment by sarayourfriend** [comment] 2022-04-15 12:44
I've got a fix for it with tests in a bit!

**Closed** 2022-04-18 10:24 UTC
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface
