### ISSUE TITLE
PO file is not regenerated when directories are renamed

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1051] opened 2022-03-04 04:54 UTC
## Description

The `pre-commit` action configured by `husky` only generates the PO file when the `en.json` file is changed. But the PO file also changes when directories are named in the code, as that affects the usage of the translations.

This means that there could be events like this:
- Developer changes usage of string from `en.json`.
- Developer lints the code which does not generate the PO file.
- Developer commits this to Git.
- CI check on GitHub flags this as a lint failure.

## Expectation

The PO file generation should be able to identify other cases where it can be changed. At least it should be able to catch the same changes as the CI job does, to prevent commits from reaching GitHub and failing there.

## Additional context

If the PO generation is fast, we could just do it for every commit.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment] 2022-03-04 10:55
Especially now that the PO file is diffed to ensure it's only written when there are _actual_ changes, this makes sense!

**Comment by sarayourfriend** [comment] 2022-03-04 13:11
Can we take the strategy from the CI and apply it to the pre-commit hook? :thinking: I think it would cover this case as well right?

**Comment by krysal** [comment] 2022-03-11 13:31
I can't reproduce the issue, could you provide the steps, perhaps with specific directory & file names to try?

**Comment by sarayourfriend** [comment] 2022-06-17 06:21
In @obulat's PR to update the POT file on every commit, I realized that I think we can just store the POT file and generated translation files (everything that isn't the `en.json`) in a separate, special and protected branch that is pushed to exclusively by a GH action every time main is merged too.

**Comment by sarayourfriend** [comment] 2022-06-17 06:21
@dhruvkb do you want to continue working on this issue or do you mind if I assign it to myself to implement the action I'm describing? Alternatively you can work on it as well.

**Comment by dhruvkb** [comment] 2022-06-17 06:27
You can take this up @sarayourfriend.

**Comment by krysal** [comment] 2022-06-17 14:18
Saying it again, I _couldn't_ reproduce the problem, were you able to do it @sarayourfriend? I'm curious about how.

**Closed** 2022-06-29 13:55 UTC
Labels: good first issue, help wanted, 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx
