### ISSUE TITLE
Open external links in parent frame

### ISSUE THREAD

**Issue by dd32** [WordPress/openverse-frontend#983] opened 2022-02-22 06:32 UTC
## Description
The https://creativecommons.org/licenses/ link on the homepage is unclickable when loading via the WordPress.org/openverse iframe.

Reported here: https://meta.trac.wordpress.org/ticket/6124

## Reproduction

1. Visit https://wordpress.org/openverse/
2. Click [Creative Commons license](https://creativecommons.org/licenses/)
3. See refused error.

## Expectation
Load in parent frame.

## Screenshots
See ticket

**Comment by sarayourfriend** [comment] 2022-02-22 10:40
Once #871 is deployed (hopefully within the next couple weeks) this should be fixed.

**Comment by obulat** [comment] 2022-02-22 11:46
Thank you for reporting this issue, @dd32 ! I am going to close it as a duplicate of #468 and because it's fixed in #879 (to be deployed)

**Closed by obulat** 2022-02-22 11:46 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
