### ISSUE TITLE
Layout error in the hero search button in some locales

### ISSUE THREAD

**Issue by t-hamano** [WordPress/openverse-frontend#1136] opened 2022-03-18 01:58 UTC
## Description

I have found a small layout error in the hero image in some locales.

## Reproduction

This may occur in other locales.

### On https://fr.wordpress.org/openverse

- Text protrudes from the button.

![fr](https://user-images.githubusercontent.com/54422211/158922837-dc326676-232a-4377-b8a7-45ec525d4272.png)

### On https://ja.wordpress.org/openverse/

- The letters on the buttons are vertically aligned.
- Gallery images are placed above the search box at certain browser widths,

https://user-images.githubusercontent.com/54422211/158922847-85a81c72-ef82-46d5-99ea-5f5c8f82fcee.mp4

## Expectation

I believe the following modifications are needed:

- Increase `z-index` value of `header` components
- Change the `width` of the search button to auto and insert left/right padding instead.

## Environment

 - Device: Laptop
 - OS: Windows 11
 - Browser: Google Chrome 99.0.4844.51

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

I have yet to contribute to this project, but I am sure it can be fixed with just a CSS change, so I want to try.😃

**Comment by obulat** [comment] 2022-03-18 04:10
Thank you for reporting this, @t-hamano ! This is actually a duplicate of #895, but since you have more screenshots and details, I will close that issue instead.
Welcome to Openverse, we are excited to see your contributions!

**Comment by t-hamano** [comment] 2022-03-18 04:25
Oh, sorry I didn't check the issue enough.
I would like to submit a PR within a couple of days 👍

**Comment by obulat** [comment] 2022-03-18 09:28
No problem, @t-hamano ! Thank you!

**Closed** 2022-03-21 15:21 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface, 🔧 tech: vue, 🎨 tech: css
