### ISSUE TITLE
Storybook issues

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#483] opened 2021-12-03 20:56 UTC
## Description

The Storybook is not showing the stories written on `.mdx` files and the ability to change props with _knobs_ is not visible. I'm not sure with what changes this started to happen.

## Reproduction

1. Just run `npm run storybook`
2. Go to the open browser windows obverse there is not showing the index page
3. Search for the `VLicense` story for example and see it's not found neither

## Expectation

We want to show these stories too, using this format is especially important because it enables us to add documentation about the components.

## Screenshots

![CleanShot 2021-12-03 at 16 50 49@2x](https://user-images.githubusercontent.com/9145885/144671116-0b8af816-70e7-4d4b-9279-bb7c695f6fa1.png)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment] 2021-12-06 05:18
I wasn't able to fix this yet, unfortunately. All I could find that at the moment before the docker-improvements branch was merged) the mdx files were built fine: https://github.com/WordPress/openverse-frontend/tree/7042449170caec9dda9716cc3236c4261229721a . And the issue is that `@storybook/addon-essentials` cannot be resolved.
A very crazy workaround I've been using is to checkout the code before the `docker_improvements` branch, remove node_modules, run `npm install`, then checkout my branch (header) and run storybook :)

**Comment by dhruvkb** [comment] 2021-12-06 11:47
An alternative workaround (discovered by comparing the `node_modules/` directory structure before and after commit 7042449) is by moving Storybook dependencies from the Nuxt Storybook’s internal node-modules to the upper level.

```bash
$ mv node_modules/@nuxtjs/storybook/node_modules/@storybook/addon-essentials node_modules/@storybook
$ mv node_modules/@nuxtjs/storybook/node_modules/@storybook/addon-docs node_modules/@storybook
```

I still have no idea why the folder structure changed but it seems to be some dependency conflict which causes these two packages to into a subfolder. The rest don’t conflict and they are placed normally. Since moving these folders to their expected location fixes the issue, whatever the conflict is must be largely superficial.

**Comment by zackkrida** [comment] 2021-12-06 13:59
I haven't looked but I wonder if it's possible there was a nuxt storybook minor upgrade that actually had a breaking change. I know the package lock was rebuilt when the docker branch was merged

**Comment by dhruvkb** [comment] 2021-12-07 15:43
What I'm going to do (in my next debugging-friendly time slot) is remove our packages one by one till it starts working and then add them back one by one.

**Comment by sarayourfriend** [comment] 2021-12-13 20:16
Is this potentially just a problem with how NPM handles module resolution? I think Yarn or pnpm might do things differently... this definitely reminds me of some of the wacky issues I've seen with NPM dependency resolution in Gutenberg and in Calypso when I worked on that previously as well. Calypso eventually moved to Yarn to address those issues.

**Comment by zackkrida** [comment] 2021-12-13 20:21
I'd be very curious to see if switching to yarn fixes this 'automatically', @sarayourfriend

**Comment by dhruvkb** [comment] 2021-12-14 05:04
At least we know the problem now.

I personally don't like Yarn, especially after what they did with v2, but if it is better at resolving dependencies (which is the one core thing for package managers), I'm all for it.

**Comment by obulat** [comment] 2021-12-14 05:12
Apparently, there is a workaround module for nuxt that makes it possible to install only postcss8: https://github.com/nuxt/postcss8 . And it is created by nuxt contributors

**Comment by obulat** [comment] 2021-12-14 05:28
There is also [this issue](https://github.com/nuxt-community/storybook/issues/341#issuecomment-989057731) for `nuxt/storybook`:
Adding to this: @nuxtjs/storybook v 4.2.0 bumbed the css-loader dependency from ^5.2.6 to ^6.5.1. As css-loader 6.0.0 dropped support for webpack 4 this is a breaking change.

**Comment by sarayourfriend** [comment] 2021-12-14 15:15
> I personally don't like Yarn, especially after what they did with v2, but if it is better at resolving dependencies (which is the one core thing for package managers), I'm all for it.

Yeah I'm not stoked about Yarn v2 either but we can just stick with v1, it's not going anywhere anytime soon 🙂 Or we can try pnpm too, it has some really interesting properties including massive bandwidth saving advantages which I think is pretty compelling!

**Closed** 2021-12-15 14:35 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
