### ISSUE TITLE
Home page Images are cutting in the smaller devices

### ISSUE THREAD

**Issue by HILAYTRIVEDI** [WordPress/openverse-frontend#1209] opened 2022-03-31 12:24 UTC
## Description
On the open verse home page, the images are getting cut into smaller devices.

## Reproduction
1. Visit: https://wordpress.org/openverse/
2. Change the screen viewport to the mobile devices.
3. You will notice that the images are getting cut.

## Screenshots
https://prnt.sc/ttzyWsP-YLKM

## Resolution
- [x] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment] 2022-03-31 12:39
This is actually an intentional part of the design @HILAYTRIVEDI. I'll see if our designer @panchovm has any thoughts, however.

**Comment by HILAYTRIVEDI** [comment] 2022-03-31 13:01
Okay @zackkrida, Thanks for the update. My point here is that the division has enough height for all the images. And also it looks kind of wierd.

**Comment by HILAYTRIVEDI** [comment] 2022-03-31 13:16
#1211 This PR can fix this issue.

**Comment by sarayourfriend** [comment] 2022-04-04 06:22
I don't believe there's enough room for all the images to show without them shrinking very small.

Unless @panchovm disagrees I think we should close this as working as intended.

**Comment by panchovm** [comment] 2022-04-04 16:12
I do not see the cutting effect as a problem since devices have different viewports.

Your proposal @HILAYTRIVEDI adds a white space that pushes the footer downwards without an apparent reason. The current solution solves the idea of introducing sample results without depending on any crucial interaction.

**Comment by HILAYTRIVEDI** [comment] 2022-04-05 04:21
Hi @panchovm, Thanks for looking into this. So should I close this PR then?

**Comment by sarayourfriend** [comment] 2022-04-05 05:17
Yes, thanks for keeping an eye out for bugs @HILAYTRIVEDI but this one is working as intended. Thanks for confirming, Francisco!

**Closed by sarayourfriend** 2022-04-05 05:17 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
